### ISSUE TITLE
Invalid key registration response 

### ISSUE THREAD

**Issue by dragonxtek** [miguelgrinberg/flask-webauthn-demo#1]
When I tried to create a key, I can't
![Screenshot from 2022-08-29 16-48-08](https://user-images.githubusercontent.com/10552658/187296134-d213b922-0102-4f3b-8b34-feb66c4b7e96.png)

**Comment by miguelgrinberg** [comment]
Try connecting on localhost instead of 127.0.0.1. The WebAuthn protocol requires origin verification. The origin is defined in the configuration here: https://github.com/miguelgrinberg/flask-webauthn-demo/blob/main/config.py#L10.

**Comment by dragonxtek** [comment]
Thanks, now it's work
